### ISSUE TITLE
config in sls yml doesn't work if imported from another file

### ISSUE THREAD

**Issue by manwaring** [manwaring/serverless-plugin-iam-checker#14]
commented out doesn't work - values not getting set
```yml
  # iamChecker: ${self:custom.config.iamChecker}
  iamChecker:
    actions:
      allowWildcardOnly: true
      allowWildcards: true
      allowedPatterns: []
    resources:
      allowWildcardOnly: true
      allowedPatterns: []
      allowedReferences: []
```
